baseURL: https://purvasikri.netlify.app/
languageCode: en-us
title: Portfolio website by Purva Sikri
theme: forty
googleAnalytics: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A GLIMPSE OF SELECTED ANALYTICAL PROBLEMS SOLVED BY PURVA SIKRI.
    title: Research and Analytics with Purva 
  blog: {}
  contact:
    address:
      - city: London, NW89NY
        country: United Kingdom.
        street: Halll Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: psikri.mam2022@london.edu
        title: Email ID
    enable: yes
    phone:
      - phone: (+44) 07376136866
        title: Phone
  custom_css: []
  custom_js: []
  description: With knowledge of softwares like R-Studio, Python, SQL, and Tableau, I am also a CMA, CFA second level candidate, and KPMG certified accountant. Further, my hobbies subsume athletics (), swimming, and travelling.   
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/purvasikri
      - icon: fa-github
        label: GitHub
        url: https://github.com/Purvasikri/my_website.git
      - icon: fa-linkedin
        label: LinkedIn
        url: www.linkedin.com/in/purvasikriconsulting
  image: ''
  name: Purva Sikri
  navigation:
    button1:
      - name: Main menu
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: About me
        url: blogs/purva
      - name: Research papers 
        url: blogs/magna
      - name: R projects
        url: blogs/blockchain
      - name: Python projects
        url: blogs/python
    menu: Menu
    #subtitle: 
    title: Purva Sikri
  tiles:
    enable: yes
    showcase:
      - image: picblog.png
        subtitle: A professional introduction and authored articles  
        title: About me
        slug: purva
        url: blogs/purva
      - image: lbs.png
        subtitle: A university group project (ggplot, t-test, and hypothesis testing).
        title: R-studio data analytics
        url: blogs/blockchain
      - image: rti2.png
        subtitle: 1. Cognitive capture (Finance)              
                  2. Right to information (Social)
        title: Published research papers - Financial and Social.
        url: blogs/magna
      - image: lbss.png
        subtitle: A university group project with multiple datasets (Tidyverse, dplyr, ggplot, and t-test; using bootstrap).
        title: R for data science 
        url: blogs/rti1
      - image: iim.png
        subtitle: A python project subsuming topics such as AUC, ROC, logistic regression, and decision tree classifiers to check whether banks
                  should use target advertising to attract prospective profitable clients.
        title: Target Banking in India (making the most of the 20% profitable customers; the 80-20 rule).
        url: https://drive.google.com/file/d/1BpuBM3TcjmIyCdv9k0CO1GEFk85mYrg9/view?usp=sharing
      - image: IBM2.png
        subtitle: In an All-India case study competition, we created a simulation for IBM and Maersk; Tradelens and performed a cost-benefit analysis to see whether it should adopt blockchain for operations.
        title: Cost-benefit analysis of blockchain for logistic companies.  
        url: blogs/last1
  two:
    buttonText: Blog description 
    enable: yes
    subtitle: ""
    title: Thank you
    url: blogs
    

