baseURL: https://purvasikri.netlify.app/
languageCode: en-us
title: Portfolio website by Purva Sikri
theme: forty
googleAnalytics: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      WEBSITE DESIGNED 
      AND RELEASED BY PURVA SIKRI.
    title: Portfolio website by Purva Sikri
  blog: {}
  contact:
    address:
      - city: London, NW89NY
        country: United Kingdom.
        street: Halll Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: psikri.mam2022@london.edu
        title: Email ID
    enable: yes
    phone:
      - phone: (+44) 07376136866
        title: Phone
  custom_css: []
  custom_js: []
  description: With knowledge of softwares like R-Studio, Python, SQL, and Tableau, I am also a CMA, CFA second level candidate, and KPMG certified accountant. Further, my hobbies subsume athletics (), swimming, and travelling.   
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/purvasikri
      - icon: fa-github
        label: GitHub
        url: https://github.com/Purvasikri/my_website.git
      - icon: fa-linkedin
        label: LinkedIn
        url: www.linkedin.com/in/purvasikriconsulting
  image: ''
  name: Purva Sikri
  navigation:
    button1:
      - name: Main Menu
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: About me
        url: blogs/purva
      - name: Research papers 
        url: blogs/magna
      - name: R projects
        url: blogs/blockchain
      - name: Pyhon projects
        url: blogs/python
    menu: Menu
    #subtitle: By HTML5 Up
    #title: 
  tiles:
    enable: yes
    showcase:
      - image: picblog.png
        subtitle: A short Introduction
        title: About me
        slug: purva
        url: blogs/purva
      - image: ggplot2.png
        subtitle: Data analysis
        title: R-studio data analytics
        url: blogs/blockchain
      - image: paraRTI.png
        subtitle: Cognitive capture and Right to information 
        title: Research papers - Financial and Social
        url: blogs/magna
      - image: blog_4pic.png
        subtitle: Tidyverse, dplyr, ggplot, and t-test (using bootstrap).
        title: Rmarkdown projects 
        url: blogs/rti1
      - image: IMPnew.png
        subtitle: Target banking in India
        title: Python projects
        url: https://drive.google.com/file/d/1uVPM-jeMgNJ81DbXeu_kILqD7r6iOPp6/view?usp=sharing
      - image: IBM.png
        subtitle: A simulation for IBM and Maersk 
        title: Cost-benefit analysis of blockchain 
        url: https://drive.google.com/file/d/1EERD8I1ggbvxTW4CCI_YMs6oz4iPmD2C/view?usp=sharing
  two:
    buttonText: Blog description 
    enable: yes
    subtitle: ""
    title: Thank you
    url: blogs
    

