baseURL: https://purvasikri.netlify.app/
languageCode: en-us
title: Portfolio website DSDSDF for Purva Sikri
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      THE FIRST (1) WEBSITE DESIGNED
      AND RELEASED BY PURVA SIKRI.
    title: Hi, my name is Purva Sikri
  blog: {}
  contact:
    address:
      - city: London, NW8 9NY
        country: United Kingdom
        street: Halll Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: psikri.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 07376136866
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/purvasikri
      - icon: fa-github
        label: GitHub
        url: https://github.com/Purvasikri/my_website.git
      - icon: fa-linkedin
        label: LinkedIn
        url: www.linkedin.com/in/purvasikriconsulting
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    #subtitle: By HTML5 Up
    #title: 
  tiles:
    enable: yes
    showcase:
      - image: blog1_website.jpeg
        subtitle: A short Introduction
        title: About me
        slug: purva
        url: blogs/purva
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
    

